import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "./_components/query-provider";
import { AnimatedPage } from "./_components/animated-page";
import { cn } from "@/lib/utils";
import { AppThemeProvider } from "./_components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: "/favicon.png",//point to favicon.png in public
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(geistMono.variable, geistSans.variable)}>
        <QueryProvider>
          <AppThemeProvider>
            <AnimatedPage>{children}</AnimatedPage>
          </AppThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
